filters:
  min_winrate: 10
  min_pnl: 100
  min_tokens_traded: 5
  max_tokens_traded: 100000

  # if both are true it will filter based on both 7d and 30d data
  # if wallet didnt trade in selected period, it will be filtered out
  use_7d_data: false # if true, above filters will be applied to 7d data
  use_30d_data: true # if true, above filters will be applied to 30d data
